<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>none</AnalysisLevel>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <AssemblyName>VoiceKit.Examples</AssemblyName>
    <RootNamespace>VoiceKit.Examples</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoiceKit.Client.csproj" />
  </ItemGroup>

</Project>
